
// Header styles
export const navbarStyles = {
    navbarHeader : {
        container: "flex items-center gap-2",
    nav: {
        container: "fixed top-0 left-0 w-full z-30 transition-all duration-300",
        wrapper: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8",
        content: "flex items-center justify-between",
        scrolled: "bg-white shadow-md py-4 lg:py-6",
        transparent: "bg-transparent py-5 lg:py-7",
    },
    leftSection: {
        container: "flex items-center gap-3",
        menuButton: "md:hidden p-2 hover:bg-gray-100 rounded-lg transition-colors",
        menuIcon: "w-6 h-6"
    },
    rightSection: {
        authIconContainer: "hidden md:flex items-center gap-1",
        authProfileIconContainer: "relative profile-dropdown-container",
        authMobileIconContainer: "flex md:hidden items-center gap-1",
        authMobileProfileIconContainer: "relative profile-dropdown-container",
    },
    },
    brand: {
        container: "flex items-center gap-2",
        logo: "text-2xl transition-all duration-300 rounded-lg bg-orange-300 p-1",
        title: "text-xl font-bold text-gray-800",
    },
    navLinks: {
        navLinkContainer: "hidden md:flex items-center gap-6 lg:gap-8",
        link: "font-medium text-gray-700 hover:text-orange-500 transition-colors duration-200 relative group",
        text: "absolute bottom-0 left-0 w-0 h-0.5 bg-orange-500 transition-all duration-300 group-hover:w-full",
    },
    signInBtn: {
        btn: "bg-orange-500 text-white px-6 py-2.5 rounded-full hover:bg-orange-600 transition-all duration-300 flex items-center gap-2 shadow-md hover:shadow-lg",
        icon: "w-4 h-4",
        text: "hidden lg:inline",
    },
    iconbutton: {
        btn: "relative p-2 text-gray-700 hover:text-orange-500 transition-colors duration-200 rounded-full hover:bg-orange-50",
        icon: "w-6 h-6",
        badge: "absolute -top-1 -right-1 bg-orange-500 text-white text-xs rounded-full min-w-[20px] h-5 flex items-center justify-center font-semibold px-1",
    },
    slidePanel: {
        isClosePanel: "fixed inset-0 bg-opacity-50 z-40 transition-opacity duration-300 bg-black/50 backdrop-blur-sm animate-slideDown",
        isOpenPanel: "fixed top-0 right-0 h-full w-full sm:w-[420px] lg:w-[480px] bg-white shadow-2xl z-50 transform transition-transform duration-300 ease-out",
        container: "h-full flex flex-col",
        wrapper: "flex items-center justify-between p-4 md:p-6 border-b bg-gradient-to-r from-orange-500 to-amber-500 text-white",
        title: "text-xl md:text-2xl font-bold text-white",
        btn: "p-2 hover:bg-white/20 rounded-full transition-colors",
        closeIcon: "w-6 h-6 text-white",
        content: "flex-1 overflow-y-auto",
        panelFooter: "border-t border-gray-200 bg-white",
        
        cartItemPanel: {
            container: "bg-white border border-gray-200 rounded-xl p-4 hover:shadow-lg transition-all duration-200",
            innerContainer: "flex gap-4",
            imageContainer: "w-16 h-16 md:w-20 md:h-20 bg-gradient-to-br from-orange-50 to-amber-100 rounded-lg flex items-center justify-center flex-shrink-0",
            contentWrapper: "flex-1 min-w-0",
            header: "flex justify-between items-start mb-3",
            nameContainer: "flex-1 min-w-0",
            name: "font-semibold text-gray-800 truncate text-lg",
            category: "text-sm text-gray-500 mt-1",
            removeBtn: "ml-2 p-2 text-red-500 hover:bg-red-50 rounded-lg transition-colors",
            removeIcon: "w-4 h-4",
            controlsContainer: "flex items-center justify-between mt-4 pt-3 border-t border-gray-100",
            quantityControls: "flex items-center gap-3",
            quantityBtn: "w-9 h-9 rounded-full bg-gray-100 border border-gray-300 flex items-center justify-center hover:bg-orange-50 hover:border-orange-500 transition-all duration-200 active:scale-95",
            quantityBtnDisabled: "opacity-50 cursor-not-allowed hover:bg-gray-100 hover:border-gray-300",
            quantityBtnIcon: "w-4 h-4",
            quantityText: "w-8 text-center font-semibold text-gray-800",
            priceContainer: "text-right",
            unitPrice: "text-sm text-gray-500 mb-1",
            totalPrice: "font-bold text-gray-800 text-lg",
            
            // Other cart panel styles
            contentContainer: "p-4 md:p-6",
            headerContainer: "flex justify-between items-center mb-6 px-2",
            itemCount: "text-sm text-gray-600 font-medium",
            clearBtn: "text-sm text-red-500 hover:text-red-600 font-medium flex items-center gap-2 px-3 py-1.5 hover:bg-red-50 rounded-lg transition-all",
            clearIcon: "w-4 h-4",
            itemsContainer: "space-y-4",
            
            emptyState: {
                container: "text-center py-12 px-4",
                icon: "w-20 h-20 mx-auto text-gray-300 mb-6",
                title: "text-gray-600 text-xl font-medium mb-2",
                description: "text-gray-400 text-base mb-6",
                continueBtn: "inline-block px-6 py-3 bg-orange-500 text-white font-medium rounded-full hover:bg-orange-600 transition-all duration-300 hover:shadow-lg",
            },
            
            footerStyles: {
                container: "p-4 md:p-6 space-y-4",
                wrapper: "space-y-3 bg-gray-50 rounded-xl p-4",
                subtotalContainer: "flex justify-between text-base",
                subtotalLabel: "text-gray-600",
                subtotalValue: "font-semibold text-gray-800",
                discountContainer: "flex justify-between text-base text-green-600",
                taxContainer: "flex justify-between text-base",
                taxLabel: "text-gray-600",
                taxValue: "font-semibold",
                deliveryContainer: "flex justify-between text-base border-t border-gray-200 pt-3",
                totalContainer: "flex justify-between text-xl font-bold pt-4 border-t border-gray-200",
                totalValue: "text-orange-500",
                checkoutBtn: "w-full bg-gradient-to-r from-orange-500 to-amber-500 text-white py-4 rounded-xl font-semibold text-lg hover:from-orange-600 hover:to-amber-600 transition-all duration-300 shadow-lg hover:shadow-xl active:scale-[0.98]",
                continueBtn: "w-full border-2 border-gray-300 text-gray-700 py-4 rounded-xl font-medium hover:bg-gray-50 transition-all duration-200",
            },
            orderForm: {
                container: "p-4 md:p-6",
                form: "space-y-6",
                section: "bg-white border border-gray-200 rounded-2xl p-5 hover:border-orange-200 transition-all duration-200",
                sectionTitle: "flex items-center gap-3 font-semibold text-gray-800 text-lg mb-4",
                sectionIcon: "w-5 h-5 text-orange-500",
                
                addressGrid: "grid grid-cols-1 md:grid-cols-2 gap-3",
                addressCard: "border-2 border-gray-200 rounded-xl p-4 text-left hover:border-orange-500 transition-all duration-200",
                addressCardActive: "border-orange-500 bg-orange-50",
                addressCardHeader: "flex items-center gap-2 mb-2",
                addressIcon: "w-4 h-4 text-gray-500",
                addressType: "font-medium text-gray-700",
                addressText: "text-sm text-gray-600 line-clamp-2",
                newAddressCard: "border-2 border-dashed border-gray-300 rounded-xl p-4 flex flex-col items-center justify-center gap-2 text-gray-500 hover:text-orange-500 hover:border-orange-500 transition-all duration-200",
                plusIcon: "w-8 h-8 rounded-full border-2 border-gray-300 flex items-center justify-center text-xl",
                
                inputGrid: "grid grid-cols-1 gap-4",
                inputGroup: "space-y-2",
                label: "text-sm font-medium text-gray-700 flex items-center gap-1",
                input: "w-full px-4 py-3.5 border border-gray-300 rounded-xl focus:ring-2 focus:ring-orange-500/30 focus:border-orange-500 transition-all duration-200 placeholder:text-gray-400",
                inputHint: "text-xs text-gray-500 mt-1",
                phoneInput: "flex items-center",
                phonePrefix: "px-4 py-3.5 bg-gray-100 border border-r-0 border-gray-300 rounded-l-xl text-gray-600",
                phoneInputField: "rounded-l-none",
                textarea: "w-full px-4 py-3.5 border border-gray-300 rounded-xl focus:ring-2 focus:ring-orange-500/30 focus:border-orange-500 transition-all duration-200 resize-none placeholder:text-gray-400",
                select: "w-full px-4 py-3.5 border border-gray-300 rounded-xl focus:ring-2 focus:ring-orange-500/30 focus:border-orange-500 transition-all duration-200 bg-white",
                
                radioGroup: "space-y-3",
                radioLabel: "flex items-start gap-4 cursor-pointer p-3 border border-gray-200 rounded-xl hover:border-orange-500 transition-all duration-200",
                radioInput: "mt-1 w-5 h-5 text-orange-500 focus:ring-orange-500",
                radioContent: "flex-1",
                radioText: "font-medium text-gray-800",
                radioSubtext: "text-sm text-gray-500 mt-1",
                
                paymentOptions: "space-y-3",
                paymentOption: "flex items-center gap-4 cursor-pointer p-4 border border-gray-200 rounded-xl hover:border-orange-500 transition-all duration-200",
                paymentRadio: "w-5 h-5 text-orange-500 focus:ring-orange-500",
                paymentContent: "flex items-center gap-3 flex-1",
                paymentIcon: "text-2xl",
                paymentText: "flex-1",
                paymentTitle: "font-medium text-gray-800",
                paymentDesc: "text-sm text-gray-500 mt-1",
                
                actions: "flex gap-3 pt-4",
                backBtn: "flex-1 py-3.5 border-2 border-gray-300 text-gray-700 rounded-xl font-medium hover:bg-gray-50 transition-all duration-200 active:scale-95",
                submitBtn: "flex-1 bg-gradient-to-r from-orange-500 to-amber-500 text-white py-3.5 rounded-xl font-semibold hover:from-orange-600 hover:to-amber-600 transition-all duration-300 shadow-lg hover:shadow-xl active:scale-95 flex items-center justify-center gap-2",
                submitBtnLoading: "opacity-80 cursor-not-allowed",
                spinner: "w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin",
            },       
            orderSummary: {
                container: "p-4 md:p-6 space-y-6",
                loadingContainer: "flex flex-col items-center justify-center py-12",
                spinner: "w-12 h-12 border-4 border-orange-200 border-t-orange-500 rounded-full animate-spin mb-4",
                loadingText: "text-gray-500",
                
                successHeader: "text-center py-6",
                successIconContainer: "w-20 h-20 bg-gradient-to-br from-green-100 to-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4",
                successIcon: "w-12 h-12 text-emerald-500",
                successTitle: "text-2xl font-bold text-gray-800 mb-2",
                successSubtitle: "text-gray-600",
                
                trackingSection: "bg-gradient-to-br from-orange-50 to-amber-50 rounded-2xl p-5",
                sectionTitle: "font-semibold text-gray-800 text-lg mb-5",
                timeline: "space-y-4",
                timelineStep: "relative",
                timelineContent: "flex items-center gap-4",
                stepIcon: "w-12 h-12 rounded-full flex items-center justify-center border-2",
                stepIconActive: "border-orange-500 bg-white text-orange-500",
                stepIconInactive: "border-gray-300 bg-gray-100 text-gray-400",
                stepInfo: "flex-1",
                stepLabel: "font-medium text-gray-800 block",
                stepTime: "text-sm text-gray-500 block mt-1",
                connector: "h-6 border-l-2 border-dashed border-gray-300 ml-6",
                connectorActive: "border-orange-500",
                etaContainer: "flex items-center gap-2 mt-6 pt-5 border-t border-orange-200",
                etaIcon: "w-5 h-5 text-orange-500",
                etaText: "text-gray-700",
                
                detailsSection: "bg-white border border-gray-200 rounded-2xl p-5",
                detailsGrid: "grid grid-cols-1 md:grid-cols-2 gap-4",
                detailItem: "flex items-start gap-3",
                detailIcon: "w-10 h-10 rounded-full bg-gray-100 flex items-center justify-center text-gray-500 flex-shrink-0",
                detailLabel: "text-sm text-gray-500 mb-1",
                detailValue: "font-medium text-gray-800",
                instructions: "mt-4 pt-4 border-t border-gray-100",
                instructionsLabel: "text-sm text-gray-500 mb-1",
                instructionsText: "text-gray-700 italic",
                
                itemsSection: "bg-white border border-gray-200 rounded-2xl p-5",
                itemsList: "space-y-3",
                orderItem: "flex items-center gap-4 p-3 border border-gray-100 rounded-xl hover:bg-gray-50 transition-colors",
                itemImage: "flex-shrink-0",
                imagePlaceholder: "w-12 h-12 rounded-lg bg-gradient-to-br from-orange-100 to-amber-100 flex items-center justify-center font-bold text-orange-600",
                itemDetails: "flex-1 min-w-0",
                itemHeader: "flex justify-between items-start mb-1",
                itemName: "font-medium text-gray-800 truncate",
                itemQuantity: "text-sm text-gray-500 bg-gray-100 px-2 py-1 rounded",
                itemCategory: "text-sm text-gray-500 mb-2",
                itemFooter: "flex justify-between items-center",
                itemPrice: "font-semibold text-gray-800",
                itemRating: "text-sm text-amber-500 bg-amber-50 px-2 py-1 rounded",
                
                priceSection: "bg-white border border-gray-200 rounded-2xl p-5",
                priceBreakdown: "space-y-3",
                priceRow: "flex justify-between text-gray-600",
                discount: "text-green-600 font-medium",
                totalRow: "border-t border-gray-200 pt-3 text-lg font-bold text-gray-800 mt-3",
                totalAmount: "text-orange-500 text-xl",
                paymentRow: "border-t border-gray-200 pt-3 mt-3 text-sm",
                paymentMethod: "font-medium text-gray-700",
                
                supportSection: "text-center bg-gradient-to-r from-gray-50 to-gray-100 rounded-2xl p-5",
                supportTitle: "font-medium text-gray-800 mb-2",
                supportText: "text-gray-600 mb-2",
                supportNote: "text-sm text-gray-500",
                
                actions: "flex gap-3",
                trackBtn: "flex-1 py-3.5 border-2 border-gray-300 text-gray-700 rounded-xl font-medium hover:bg-gray-50 transition-all duration-200",
                newOrderBtn: "flex-1 bg-gradient-to-r from-orange-500 to-amber-500 text-white py-3.5 rounded-xl font-semibold hover:from-orange-600 hover:to-amber-600 transition-all duration-300",
            },
        },
        
        ordersPanelStyles : {
            contentContainer: "p-4 space-y-3",
            
            orderItem: {
                container: "bg-white border border-gray-200 rounded-xl p-4 hover:shadow-md transition-all",
                header: "flex justify-between items-start mb-3",
                orderInfo: "",
                orderNumber: "font-bold text-gray-800",
                orderDate: "text-sm text-gray-500",
                statusBadge: "px-3 py-1.5 rounded-full text-xs font-semibold flex items-center gap-1.5",
                statusIcon: "w-3.5 h-3.5",
                itemsContainer: "space-y-2 mb-3",
                itemsTitle: "text-sm text-gray-600 font-medium",
                itemsList: "text-sm text-gray-700 ml-2",
                itemBullet: "truncate",
                footer: "flex justify-between items-center pt-3 border-t",
                total: "font-bold text-lg text-gray-800",
                cancelBtn: "text-sm text-red-500 hover:text-red-600 font-medium flex items-center gap-1 hover:bg-red-50 px-3 py-1.5 rounded-lg transition-all",
                cancelIcon: "w-4 h-4",
            },
            
            statusStyles: {
                delivered: { bg: 'bg-green-100', text: 'text-green-700' },
                preparing: { bg: 'bg-orange-100', text: 'text-orange-700' },
                on_the_way: { bg: 'bg-blue-100', text: 'text-blue-700' },
                cancelled: { bg: 'bg-red-100', text: 'text-red-700' },
            },
            
            emptyState: {
                container: "text-center py-12",
                icon: "w-16 h-16 mx-auto text-gray-300 mb-4",
                title: "text-gray-500 text-lg font-medium",
                description: "text-gray-400 text-sm mt-2",
            },
        },
        bookingsPanelStyles : {
            contentContainer: "p-4 space-y-3",
            
            bookingItem: {
                container: "bg-white border border-gray-200 rounded-xl p-4 hover:shadow-md transition-all",
                header: "flex justify-between items-start mb-3",
                restaurantName: "font-bold text-gray-800 text-lg",
                statusBadge: "px-3 py-1.5 rounded-full text-xs font-semibold flex items-center gap-1.5",
                statusIcon: "w-3.5 h-3.5",
                detailsContainer: "space-y-2 mb-3",
                detailItem: "flex items-center gap-2 text-sm text-gray-600",
                detailIcon: "w-4 h-4 text-gray-400",
                specialRequestContainer: "bg-orange-50 rounded-lg p-2 mt-2",
                specialRequestTitle: "text-xs text-orange-700 font-medium",
                specialRequestText: "text-sm text-gray-700",
                cancelBtn: "w-full mt-3 text-sm text-red-500 hover:text-red-600 font-medium flex items-center justify-center gap-2 hover:bg-red-50 py-2 rounded-lg transition-all border border-red-200",
                cancelIcon: "w-4 h-4",
            },
            
            statusStyles: {
                confirmed: { bg: 'bg-green-100', text: 'text-green-700' },
                pending: { bg: 'bg-orange-100', text: 'text-orange-700' },
                completed: { bg: 'bg-gray-100', text: 'text-gray-700' },
                cancelled: { bg: 'bg-red-100', text: 'text-red-700' },
            },
            
            emptyState: {
                container: "text-center py-12",
                icon: "w-16 h-16 mx-auto text-gray-300 mb-4",
                title: "text-gray-500 text-lg font-medium",
                description: "text-gray-400 text-sm mt-2",
            },
        },
    },
    modal: {
        container: "fixed inset-0 z-50 flex items-center justify-center p-4",
        closeBtn: "absolute inset-0 bg-opacity-50 transition-opacity",
        wrapper: "relative bg-white rounded-2xl shadow-2xl w-full max-h-[90vh] overflow-hidden animate-slideDown transition-animate delay-150 duration-300",
        header: "flex items-center justify-between p-4 sm:p-6 bg-amber-500",
        title: "text-xl sm:text-2xl font-bold text-gray-50",
        headerBtn: "p-2 hover:bg-white rounded-full transition-colors",
        closeIcon: "w-6 h-6 text-gray-800 bg-white rounded-full p-1",
        contentContainer: "overflow-y-auto max-h-[calc(90vh-5rem)]",

        profileModal: {
            container: "p-4 sm:p-6 space-y-6",
            avatarContainer: "flex flex-col items-center space-y-4",
            avatarWrapper: "relative",
            avatar: "w-24 h-24 sm:w-32 sm:h-32 bg-gradient-to-br from-orange-400 to-orange-600 rounded-full flex items-center justify-center text-white text-4xl sm:text-5xl font-bold shadow-lg",
            isEdit: "absolute bottom-0 right-0 bg-orange-500 text-white p-2 rounded-full shadow-lg hover:bg-orange-600 transition-colors",
            isEditIcon: "w-4 h-4",
            isNotEdit: "flex items-center gap-2 text-orange-500 hover:text-orange-600 font-medium transition-colors",
            isNotEditIcon: "w-4 h-4",
            
            formContainer: "space-y-4",
            label: "block text-sm font-semibold text-gray-700 mb-2",
            inputContainer: "relative",
            inputIcon: "absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400",
            input: "w-full pl-11 pr-4 py-3 border rounded-xl transition-all",
            textArea: "w-full pl-11 pr-4 py-3 border rounded-xl transition-all resize-none",

            isEditBtnContainer: "flex flex-col sm:flex-row gap-3 pt-4",
            isSaveBtn: "flex-1 bg-orange-500 text-white py-3 rounded-xl font-semibold hover:bg-orange-600 transition-all duration-300 flex items-center justify-center gap-2 shadow-md hover:shadow-lg",
            isConcelBtn: "flex-1 bg-gray-100 text-gray-700 py-3 rounded-xl font-semibold hover:bg-gray-200 transition-all duration-300",
            isSaveBtnIcon: "w-5 h-5",
        },
        likeModal: {
            container: "p-4 sm:p-6",
            sortContainer: "flex flex-wrap items-center justify-between gap-3 mb-6",
            title: "text-gray-600 font-medium",
            dropDown: "px-4 py-2 border border-gray-300 rounded-lg outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-200 transition-all",

            itemGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4",
            itemContainer: "group bg-white border border-gray-200 rounded-xl overflow-hidden hover:shadow-lg transition-all duration-300",
            itemWrapper: "relative bg-gradient-to-br from-orange-50 to-orange-100 p-8",
            knifeIcon: "text-6xl text-center",
            likeBtn: "absolute top-2 right-2 bg-white text-red-500 p-2 rounded-full shadow-md transition-all",
            likeIcon: "w-4 h-4 fill-current",

            contentContainer: "p-4 space-y-3",
            itemName: "font-bold text-gray-800 text-lg mb-1",
            categoryBadge: "flex items-center justify-between text-sm text-gray-600",
            category: "bg-orange-50 text-orange-700 px-2 py-1 rounded-full font-medium",

            ratingContainer: "flex items-center gap-1",
            ratingIcon: "text-yellow-500",
            rating: "font-semibold",

            priceContainer: "flex items-center justify-between pt-2 border-t",
            price: "text-2xl font-bold text-orange-500",
            priceIcon: "inline-block",

            addCartBtn: "bg-orange-500 text-white px-4 py-2 rounded-full font-medium hover:bg-orange-600 transition-all duration-300 flex items-center gap-2 shadow-md hover:shadow-lg",
            addCartIcon: "w-4 h-4",

            likeCountContainer: "flex items-center gap-1 text-xs text-gray-500",
            likeCountIcom: "w-3 h-3",

            noFavoriteContainer: "text-center py-12",
            noFavoriteIcon: "w-16 h-16 mx-auto text-gray-300 mb-4",
            noFavoriteDescription1: "text-gray-500 text-lg font-medium",
            noFavoriteDescription2: "text-gray-400 text-sm mt-2",
        },
    },
    profileDropdownStyles: {
        container: "absolute top-full right-0 mt-2 w-72 bg-white rounded-xl shadow-xl border border-gray-200 overflow-hidden z-50 animate-slideDown",
        header: {
            container: "bg-gradient-to-r from-orange-50 to-orange-100 px-4 py-4 border-b-1 border-gray-800",
            innerContainer: "flex items-center gap-3",
            avatar: "w-12 h-12 bg-gradient-to-br from-orange-400 to-orange-600 rounded-full flex items-center justify-center text-white text-xl font-bold flex-shrink-0",
            userInfo: "flex-1 min-w-0",
            name: "font-bold text-gray-800 truncate",
            email: "text-sm text-gray-600 truncate",
        },
        sections: {
            container: "py-2 border-b-1 border-gray-800",
            title: "px-4 py-2 text-xs font-bold text-gray-500 uppercase tracking-wider",
            button: "w-full flex items-center gap-3 px-4 py-2.5 hover:bg-orange-50 transition-colors text-left",
            icon: "w-4 h-4 text-gray-600",
            text: "text-sm text-gray-700 font-medium",
            link: "flex items-center gap-3 px-4 py-2.5 hover:bg-orange-50 transition-colors",
        },
        footer: {
            container: "p-2",
            logoutBtn: "w-full flex items-center justify-center gap-2 py-2.5 text-red-600 hover:bg-red-50 rounded-lg transition-all font-medium",
            logoutIcon: "w-4 h-4",
            logoutText: "text-sm",
        },
    },
    mobileDrawerStyles: {
        overlay: "fixed inset-0 bg-opacity-50 z-40 md:hidden",
        drawer: "fixed top-0 left-0 h-full w-80 bg-white shadow-2xl z-50 transform transition-transform duration-300 md:hidden",
        drawerOpen: "translate-x-0",
        drawerClosed: "-translate-x-full",
        header: {
        container: "flex items-center justify-between p-4",
        title: "font-bold text-gray-800 text-lg",
        closeBtn: "p-2 hover:bg-gray-100 rounded-full transition-colors",
        closeIcon: "w-5 h-5",
        },
        userSection: {
        container: "bg-gradient-to-r from-orange-50 to-orange-100 p-4",
        innerContainer: "flex items-center gap-3",
        avatar: "w-14 h-14 bg-gradient-to-br from-orange-400 to-orange-600 rounded-full flex items-center justify-center text-white text-xl font-bold flex-shrink-0",
        userInfo: "flex-1 min-w-0",
        name: "font-bold text-gray-800 truncate",
        email: "text-sm text-gray-600 truncate",
        },
        content: {
            container: "flex-1 overflow-y-auto pb-4",
            section: "space-y-1 px-2 mb-4",
            title: "px-2 pt-2 text-xs font-bold text-gray-500 uppercase tracking-wider",
            navLink: "block px-4 py-3 rounded-lg hover:bg-orange-50 text-gray-700 font-medium transition-colors",
            actionButton: "w-full flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-orange-50 text-gray-700 font-medium transition-colors",
            actionIcon: "w-5 h-5 text-gray-500",
            divider: "my-4",
        },
        footer: {
        container: "p-4",
        logoutBtn: "w-full flex items-center justify-center gap-2 py-3 bg-red-50 text-red-600 rounded-xl font-semibold hover:bg-red-100 transition-colors",
        logoutIcon: "w-5 h-5",
        },
    },   
}