
// Header styles
export const navbarStyles = {
    navbarHeader : {
        container: "flex items-center gap-2",
    nav: {
        container: "fixed top-0 left-0 w-full z-30 transition-all duration-300",
        wrapper: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8",
        content: "flex items-center justify-between",
        scrolled: "bg-white shadow-md py-4 lg:py-6",
        transparent: "bg-transparent py-5 lg:py-7",
    },
    leftSection: {
        container: "flex items-center gap-3",
        menuButton: "md:hidden p-2 hover:bg-gray-100 rounded-lg transition-colors",
        menuIcon: "w-6 h-6"
    },
    rightSection: {
        authIconContainer: "hidden md:flex items-center gap-1",
        authProfileIconContainer: "relative profile-dropdown-container",
        authMobileIconContainer: "flex md:hidden items-center gap-1",
        authMobileProfileIconContainer: "relative profile-dropdown-container",
    },
    },
    brand: {
        container: "flex items-center gap-2",
        logo: "text-2xl transition-all duration-300",
        title: "text-xl font-bold text-gray-800",
    },
    navLinks: {
        navLinkContainer: "hidden md:flex items-center gap-6 lg:gap-8",
        link: "font-medium text-gray-700 hover:text-orange-500 transition-colors duration-200 relative group",
        text: "absolute bottom-0 left-0 w-0 h-0.5 bg-orange-500 transition-all duration-300 group-hover:w-full",
    },
    signInBtn: {
        btn: "bg-orange-500 text-white px-6 py-2.5 rounded-full hover:bg-orange-600 transition-all duration-300 flex items-center gap-2 shadow-md hover:shadow-lg",
        icon: "w-4 h-4",
        text: "hidden lg:inline",
    },
    iconbutton: {
        btn: "relative p-2 text-gray-700 hover:text-orange-500 transition-colors duration-200 rounded-full hover:bg-orange-50",
        icon: "w-6 h-6",
        badge: "absolute -top-1 -right-1 bg-orange-500 text-white text-xs rounded-full min-w-[20px] h-5 flex items-center justify-center font-semibold px-1",
    },
    slidePanel: {
        isClosePanel: "fixed inset-0 bg-opacity-50 z-40 transition-opacity duration-300",
        isOpenPanel: "fixed top-0 right-0 h-full w-full sm:w-[400px] lg:w-[450px] bg-white shadow-2xl z-50 transform transition-transform duration-300 ",
        container: "h-full flex flex-col",
        wrapper: "flex items-center justify-between p-4 border-b bg-amber-500 text-white",
        title: "text-xl font-bold text-gray-50",
        btn: "p-2 hover:bg-white rounded-full transition-colors",
        closeIcon: "w-6 h-6 text-gray-800 bg-white rounded-full p-1",
        content: "flex-1 overflow-y-auto",
        panelFooter: "rounded-t-3xl border-t border-gray-800 bg-white",
        
        cartPanel: {
            contentContainer: "p-4",
            headerContainer: "flex justify-between items-center mb-4",
            itemCount: "text-sm text-gray-600",
            clearBtn: "text-sm text-red-500 hover:text-red-600 font-medium flex items-center gap-1",
            clearIcon: "w-4 h-4",
            itemsContainer: "space-y-3",
            
            cartItem: {
                container: "bg-white border border-gray-200 rounded-xl p-4 hover:shadow-md transition-all",
                innerContainer: "flex gap-4",
                imageContainer: "w-20 h-20 bg-gradient-to-br from-orange-50 to-orange-100 rounded-lg flex items-center justify-center text-3xl flex-shrink-0",
                contentContainer: "flex-1 min-w-0",
                header: "flex justify-between items-start mb-2",
                nameContainer: "flex-1 min-w-0",
                name: "font-semibold text-gray-800 truncate",
                category: "text-sm text-gray-500",
                removeBtn: "ml-2 p-1 text-red-500 hover:bg-red-50 rounded-lg transition-colors",
                removeIcon: "w-4 h-4",
                controlsContainer: "flex items-center justify-between",
                quantityControls: "flex items-center gap-2",
                quantityBtn: "w-8 h-8 rounded-full bg-gray-100 border border-gray-300 flex items-center justify-center hover:bg-orange-50 hover:border-orange-500 transition-colors",
                quantityBtnDisabled: "opacity-50 cursor-not-allowed",
                quantityBtnIcon: "w-4 h-4",
                quantityText: "w-10 text-center font-semibold",
                priceContainer: "text-right",
                unitPrice: "text-sm text-gray-500",
                totalPrice: "font-bold text-gray-800",
            },
            
            emptyState: {
                container: "text-center py-12",
                icon: "w-16 h-16 mx-auto text-gray-300 mb-4",
                title: "text-gray-500 text-lg font-medium",
                description: "text-gray-400 text-sm mt-2",
            },
            
            footerStyles: {
                container: "p-4 space-y-3",
                wrapper: "space-y-2",
                subtotalContainer: "flex justify-between text-sm",
                subtotalLabel: "text-gray-600",
                subtotalValue: "font-medium",
                discountContainer: "flex justify-between text-sm text-green-600",
                taxContainer: "flex justify-between text-sm",
                taxLabel: "text-gray-600",
                taxValue: "font-medium",
                totalContainer: "flex justify-between text-lg font-bold pt-2 border-t",
                totalValue: "text-orange-500",
                checkoutBtn: "w-full bg-orange-500 text-white py-3 rounded-full font-semibold hover:bg-orange-600 transition-all duration-300 shadow-md hover:shadow-lg",
            },
        },
        ordersPanelStyles : {
            contentContainer: "p-4 space-y-3",
            
            orderItem: {
                container: "bg-white border border-gray-200 rounded-xl p-4 hover:shadow-md transition-all",
                header: "flex justify-between items-start mb-3",
                orderInfo: "",
                orderNumber: "font-bold text-gray-800",
                orderDate: "text-sm text-gray-500",
                statusBadge: "px-3 py-1.5 rounded-full text-xs font-semibold flex items-center gap-1.5",
                statusIcon: "w-3.5 h-3.5",
                itemsContainer: "space-y-2 mb-3",
                itemsTitle: "text-sm text-gray-600 font-medium",
                itemsList: "text-sm text-gray-700 ml-2",
                itemBullet: "truncate",
                footer: "flex justify-between items-center pt-3 border-t",
                total: "font-bold text-lg text-gray-800",
                cancelBtn: "text-sm text-red-500 hover:text-red-600 font-medium flex items-center gap-1 hover:bg-red-50 px-3 py-1.5 rounded-lg transition-all",
                cancelIcon: "w-4 h-4",
            },
            
            statusStyles: {
                delivered: { bg: 'bg-green-100', text: 'text-green-700' },
                preparing: { bg: 'bg-orange-100', text: 'text-orange-700' },
                on_the_way: { bg: 'bg-blue-100', text: 'text-blue-700' },
                cancelled: { bg: 'bg-red-100', text: 'text-red-700' },
            },
            
            emptyState: {
                container: "text-center py-12",
                icon: "w-16 h-16 mx-auto text-gray-300 mb-4",
                title: "text-gray-500 text-lg font-medium",
                description: "text-gray-400 text-sm mt-2",
            },
        },
        bookingsPanelStyles : {
            contentContainer: "p-4 space-y-3",
            
            bookingItem: {
                container: "bg-white border border-gray-200 rounded-xl p-4 hover:shadow-md transition-all",
                header: "flex justify-between items-start mb-3",
                restaurantName: "font-bold text-gray-800 text-lg",
                statusBadge: "px-3 py-1.5 rounded-full text-xs font-semibold flex items-center gap-1.5",
                statusIcon: "w-3.5 h-3.5",
                detailsContainer: "space-y-2 mb-3",
                detailItem: "flex items-center gap-2 text-sm text-gray-600",
                detailIcon: "w-4 h-4 text-gray-400",
                specialRequestContainer: "bg-orange-50 rounded-lg p-2 mt-2",
                specialRequestTitle: "text-xs text-orange-700 font-medium",
                specialRequestText: "text-sm text-gray-700",
                cancelBtn: "w-full mt-3 text-sm text-red-500 hover:text-red-600 font-medium flex items-center justify-center gap-2 hover:bg-red-50 py-2 rounded-lg transition-all border border-red-200",
                cancelIcon: "w-4 h-4",
            },
            
            statusStyles: {
                confirmed: { bg: 'bg-green-100', text: 'text-green-700' },
                pending: { bg: 'bg-orange-100', text: 'text-orange-700' },
                completed: { bg: 'bg-gray-100', text: 'text-gray-700' },
                cancelled: { bg: 'bg-red-100', text: 'text-red-700' },
            },
            
            emptyState: {
                container: "text-center py-12",
                icon: "w-16 h-16 mx-auto text-gray-300 mb-4",
                title: "text-gray-500 text-lg font-medium",
                description: "text-gray-400 text-sm mt-2",
            },
        },
    },
    modal: {
        container: "fixed inset-0 z-50 flex items-center justify-center p-4",
        closeBtn: "absolute inset-0 bg-opacity-50 transition-opacity",
        wrapper: "relative bg-white rounded-2xl shadow-2xl w-full max-h-[90vh] overflow-hidden animate-slideDown transition-animate delay-150 duration-300",
        header: "flex items-center justify-between p-4 sm:p-6 bg-amber-500",
        title: "text-xl sm:text-2xl font-bold text-gray-50",
        headerBtn: "p-2 hover:bg-white rounded-full transition-colors",
        closeIcon: "w-6 h-6 text-gray-800 bg-white rounded-full p-1",
        contentContainer: "overflow-y-auto max-h-[calc(90vh-5rem)]",

        profileModal: {
            container: "p-4 sm:p-6 space-y-6",
            avatarContainer: "flex flex-col items-center space-y-4",
            avatarWrapper: "relative",
            avatar: "w-24 h-24 sm:w-32 sm:h-32 bg-gradient-to-br from-orange-400 to-orange-600 rounded-full flex items-center justify-center text-white text-4xl sm:text-5xl font-bold shadow-lg",
            isEdit: "absolute bottom-0 right-0 bg-orange-500 text-white p-2 rounded-full shadow-lg hover:bg-orange-600 transition-colors",
            isEditIcon: "w-4 h-4",
            isNotEdit: "flex items-center gap-2 text-orange-500 hover:text-orange-600 font-medium transition-colors",
            isNotEditIcon: "w-4 h-4",
            
            formContainer: "space-y-4",
            label: "block text-sm font-semibold text-gray-700 mb-2",
            inputContainer: "relative",
            inputIcon: "absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400",
            input: "w-full pl-11 pr-4 py-3 border rounded-xl transition-all",
            textArea: "w-full pl-11 pr-4 py-3 border rounded-xl transition-all resize-none",

            isEditBtnContainer: "flex flex-col sm:flex-row gap-3 pt-4",
            isSaveBtn: "flex-1 bg-orange-500 text-white py-3 rounded-xl font-semibold hover:bg-orange-600 transition-all duration-300 flex items-center justify-center gap-2 shadow-md hover:shadow-lg",
            isConcelBtn: "flex-1 bg-gray-100 text-gray-700 py-3 rounded-xl font-semibold hover:bg-gray-200 transition-all duration-300",
            isSaveBtnIcon: "w-5 h-5",
        },
        likeModal: {
            container: "p-4 sm:p-6",
            sortContainer: "flex flex-wrap items-center justify-between gap-3 mb-6",
            title: "text-gray-600 font-medium",
            dropDown: "px-4 py-2 border border-gray-300 rounded-lg outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-200 transition-all",

            itemGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4",
            itemContainer: "group bg-white border border-gray-200 rounded-xl overflow-hidden hover:shadow-lg transition-all duration-300",
            itemWrapper: "relative bg-gradient-to-br from-orange-50 to-orange-100 p-8",
            knifeIcon: "text-6xl text-center",
            likeBtn: "absolute top-2 right-2 bg-white text-red-500 p-2 rounded-full shadow-md transition-all",
            likeIcon: "w-4 h-4 fill-current",

            contentContainer: "p-4 space-y-3",
            itemName: "font-bold text-gray-800 text-lg mb-1",
            categoryBadge: "flex items-center justify-between text-sm text-gray-600",
            category: "bg-orange-50 text-orange-700 px-2 py-1 rounded-full font-medium",

            ratingContainer: "flex items-center gap-1",
            ratingIcon: "text-yellow-500",
            rating: "font-semibold",

            priceContainer: "flex items-center justify-between pt-2 border-t",
            price: "text-2xl font-bold text-orange-500",
            priceIcon: "inline-block",

            addCartBtn: "bg-orange-500 text-white px-4 py-2 rounded-full font-medium hover:bg-orange-600 transition-all duration-300 flex items-center gap-2 shadow-md hover:shadow-lg",
            addCartIcon: "w-4 h-4",

            likeCountContainer: "flex items-center gap-1 text-xs text-gray-500",
            likeCountIcom: "w-3 h-3",

            noFavoriteContainer: "text-center py-12",
            noFavoriteIcon: "w-16 h-16 mx-auto text-gray-300 mb-4",
            noFavoriteDescription1: "text-gray-500 text-lg font-medium",
            noFavoriteDescription2: "text-gray-400 text-sm mt-2",
        },
    },
    profileDropdownStyles: {
        container: "absolute top-full right-0 mt-2 w-72 bg-white rounded-xl shadow-xl border border-gray-200 overflow-hidden z-50 animate-slideDown",
        header: {
            container: "bg-gradient-to-r from-orange-50 to-orange-100 px-4 py-4 border-b-1 border-gray-800",
            innerContainer: "flex items-center gap-3",
            avatar: "w-12 h-12 bg-gradient-to-br from-orange-400 to-orange-600 rounded-full flex items-center justify-center text-white text-xl font-bold flex-shrink-0",
            userInfo: "flex-1 min-w-0",
            name: "font-bold text-gray-800 truncate",
            email: "text-sm text-gray-600 truncate",
        },
        sections: {
            container: "py-2 border-b-1 border-gray-800",
            title: "px-4 py-2 text-xs font-bold text-gray-500 uppercase tracking-wider",
            button: "w-full flex items-center gap-3 px-4 py-2.5 hover:bg-orange-50 transition-colors text-left",
            icon: "w-4 h-4 text-gray-600",
            text: "text-sm text-gray-700 font-medium",
            link: "flex items-center gap-3 px-4 py-2.5 hover:bg-orange-50 transition-colors",
        },
        footer: {
            container: "p-2",
            logoutBtn: "w-full flex items-center justify-center gap-2 py-2.5 text-red-600 hover:bg-red-50 rounded-lg transition-all font-medium",
            logoutIcon: "w-4 h-4",
            logoutText: "text-sm",
        },
    },
    mobileDrawerStyles: {
        overlay: "fixed inset-0 bg-opacity-50 z-40 md:hidden",
        drawer: "fixed top-0 left-0 h-full w-80 bg-white shadow-2xl z-50 transform transition-transform duration-300 md:hidden",
        drawerOpen: "translate-x-0",
        drawerClosed: "-translate-x-full",
        header: {
        container: "flex items-center justify-between p-4",
        title: "font-bold text-gray-800 text-lg",
        closeBtn: "p-2 hover:bg-gray-100 rounded-full transition-colors",
        closeIcon: "w-5 h-5",
        },
        userSection: {
        container: "bg-gradient-to-r from-orange-50 to-orange-100 p-4",
        innerContainer: "flex items-center gap-3",
        avatar: "w-14 h-14 bg-gradient-to-br from-orange-400 to-orange-600 rounded-full flex items-center justify-center text-white text-xl font-bold flex-shrink-0",
        userInfo: "flex-1 min-w-0",
        name: "font-bold text-gray-800 truncate",
        email: "text-sm text-gray-600 truncate",
        },
        content: {
            container: "flex-1 overflow-y-auto pb-4",
            section: "space-y-1 px-2 mb-4",
            title: "px-2 pt-2 text-xs font-bold text-gray-500 uppercase tracking-wider",
            navLink: "block px-4 py-3 rounded-lg hover:bg-orange-50 text-gray-700 font-medium transition-colors",
            actionButton: "w-full flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-orange-50 text-gray-700 font-medium transition-colors",
            actionIcon: "w-5 h-5 text-gray-500",
            divider: "my-4",
        },
        footer: {
        container: "p-4",
        logoutBtn: "w-full flex items-center justify-center gap-2 py-3 bg-red-50 text-red-600 rounded-xl font-semibold hover:bg-red-100 transition-colors",
        logoutIcon: "w-5 h-5",
        },
    },   
}