// section: 1
// Restaurant filter section styles
export const restaurantFilterStyles = {
    section: "min-h-screen bg-gradient-to-br from-amber-50 via-orange-50 to-pink-50 rounded-3xl overflow-hidden py-12 pt-20 md:pt-26",
    container: "p-4 md:px-10 lg:16",
    header: "bg-white shadow-sm sticky top-0 z-40",
    searchSection: "max-w-7xl mx-auto px-4 py-4 sm:px-6 lg:px-8",
    searchWrapper: "flex gap-2 items-center",
    searchInput: "flex-1 relative",
    input: "w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent",
    searchIcon: "absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400",
    filterButton: "lg:hidden flex items-center gap-2 px-4 py-3 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors",
    filterIcon: "h-5 w-5",
    mainContent: "w-full mx-auto py-6",
    layout: "flex gap-6",
    sidebar: "hidden lg:block w-64 flex-shrink-0",
    sidebarSticky: "sticky top-24 bg-white rounded-lg shadow-sm p-6 xl:max-h-[calc(100vh-120px)] overflow-y-auto",
    desktopApplyButton: "sticky w-full py-2 bg-orange-600 text-white rounded-lg font-semibold hover:bg-orange-700 transition-colors mb-4",
    restaurantGrid: "flex-1",
    grid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-4",
    card: "bg-white rounded-lg shadow-sm hover:shadow-lg transition-all duration-300 overflow-hidden cursor-pointer grid grid-rows-[auto_1fr_auto] h-full",
    cardImage: "relative h-48 overflow-hidden",
    image: "w-full h-full object-cover transform hover:scale-105 transition-transform duration-300",
    badge: "absolute top-3 left-3 flex flex-wrap gap-2",
    badgeItem: "px-2 py-1 bg-white/90 backdrop-blur-sm text-xs font-semibold rounded-full flex items-center gap-1",
    offerBadge: "absolute bottom-3 left-3 right-3 bg-amber-600 text-white text-xs font-semibold px-3 py-2 rounded-lg",
    cardContent: "p-4",
    restaurantHeader: "flex justify-between items-start mb-2",
    restaurantName: "text-lg font-bold text-gray-900 truncate",
    restaurantCount: "mb-4 font-medium",
    rating: "flex items-center gap-1 bg-green-600 text-white px-2 py-1 rounded text-sm font-semibold",
    cuisine: "text-gray-600 text-sm mb-3 truncate",
    infoGrid: "space-y-2",
    infoRow: "flex items-center gap-2 text-sm text-gray-700",
    features: "flex flex-wrap gap-2 mt-3 pt-3 border-t border-gray-100",
    featureTag: "px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded-full",
    cardFooter: "px-4 pb-4 flex gap-2",
    bookButton: "flex-1 py-2.5 bg-orange-600 text-white rounded-lg font-semibold hover:bg-orange-700 transition-colors text-sm",
    viewMenuButton: "flex-1 py-2.5 border-2 border-orange-600 text-orange-600 rounded-lg font-semibold hover:bg-orange-50 transition-colors text-sm",
    clearFiltersButton: "text-sm text-orange-600 hover:text-orange-700 font-semibold cursor-pointer",
    resultsCount: "text-sm text-gray-600 mb-4",
    filterSection: "mb-6",
    filterTitle: "text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2",
    filterOptions: "space-y-2",
    checkbox: "flex items-center gap-2 text-sm text-gray-700 cursor-pointer hover:text-orange-600 transition-colors",
    mobileFilter: "fixed inset-0 bg-black/50 z-50 lg:hidden",
    mobileFilterContent: "absolute right-0 top-0 bottom-0 w-full max-w-sm bg-white shadow-2xl overflow-y-auto",
    mobileFilterHeader: "sticky top-0 bg-white border-b border-gray-200 p-4 flex justify-between items-center",
    mobileFilterBody: "p-4",
    applyButton: "sticky bottom-0 bg-white border-t border-gray-200 p-4",
    button: "w-full py-3 bg-orange-600 text-white rounded-lg font-semibold hover:bg-orange-700 transition-colors",
    // pagination styles
    paginationContainer: "mt-8 flex justify-center",
    paginationWrapper: "flex items-center gap-2",
    paginationButton: "px-3 py-2 rounded-lg border border-gray-300 hover:bg-orange-50 hover:border-orange-300 transition-colors",
    paginationButtonActive: "bg-orange-600 text-white border-orange-600 hover:bg-orange-700",
    paginationButtonDisabled: "opacity-50 cursor-not-allowed hover:bg-transparent hover:border-gray-300",
    paginationEllipsis: "px-2 py-2 text-gray-500",
    paginationInfo: "text-sm text-gray-600 mb-4",
    checkboxInput: "w-4 h-4 accent-orange-600 cursor-pointer text-orange-600 focus:ring-2 focus:ring-orange-300 focus:ring-offset-2 focus:outline-none border-gray-300 rounded",
    radioInput: "w-4 h-4 accent-orange-600 cursor-pointer text-orange-600 focus:ring-2 focus:ring-orange-300 focus:ring-offset-2 focus:outline-none border-gray-300",
    // Modal Styles
    modalOverlay: "fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 animate-fadeIn",
    modalContent: "bg-white rounded-2xl w-full max-h-[90vh] overflow-hidden shadow-2xl animate-slideUp",
    modalContentSmall: "max-w-2xl",
    modalContentLarge: "max-w-4xl",
    modalHeader: "sticky top-0 bg-white border-b p-6 sm:p-4 border-gray-200 - flex justify-between items-start z-10",
    modalTitle: "text-xl sm:text-2xl font-bold text-gray-900",
    modalSubtitle: "text-sm text-gray-600 mt-1",
    modalCloseButton: "p-2 hover:bg-gray-100 rounded-full transition-colors flex-shrink-0 ml-4",
    modalBody: "overflow-y-auto",
    modalBodyScrolling: "max-h-[calc(90vh-80px)]", 
    modalBodyScrollingMobile: "px-6 pb-6 max-h-[calc(100vh-180px)] sm:max-h-[calc(90vh-80px)]", 
    modalBodyPadding: "p-4 sm:p-6",
    // Form Styles 
    formGrid: "grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4 md:gap-6",
    formGroup: "space-y-4 sm:space-y-6",
    formLabel: "block text-sm font-semibold text-gray-900 mb-1 sm:mb-2",
    formInput: "w-full px-3 sm:px-4 py-2.5 sm:py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-colors text-sm sm:text-base",
    formSelect: "w-full px-3 sm:px-4 py-2.5 sm:py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-colors bg-white text-sm sm:text-base",
    formTextarea: "w-full px-3 sm:px-4 py-2.5 sm:py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent resize-none transition-colors text-sm sm:text-base",
    formInfoBox: "bg-orange-50 border border-orange-200 rounded-lg p-3 sm:p-4",
    formInfoContent: "flex items-start gap-2 sm:gap-3",
    formInfoTitle: "font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base",
    formInfoList: "space-y-1 text-xs sm:text-sm text-gray-700",
    formActions: "flex flex-col sm:flex-row gap-2 sm:gap-3 pt-4 sm:pt-6",
    formButtonSecondary: "w-full px-4 sm:px-6 py-2.5 sm:py-3 border-2 border-gray-300 text-gray-700 rounded-lg font-semibold hover:bg-gray-50 transition-colors text-sm sm:text-base",
    formButtonPrimary: "w-full px-4 sm:px-6 py-2.5 sm:py-3 bg-orange-600 text-white rounded-lg font-semibold hover:bg-orange-700 transition-colors shadow-sm text-sm sm:text-base",
    // Menu Modal Styles 
    menuHeroImage: "relative h-32 sm:h-40 md:h-48 lg:h-56",
    menuImage: "w-full h-full object-cover rounded-t-2xl",
    menuImageOverlay: "absolute inset-0 bg-gradient-to-t from-black/70 to-transparent",
    menuImageContent: "absolute bottom-2 sm:bottom-3 md:bottom-4 left-3 sm:left-4 md:left-6 right-3 sm:right-4 md:right-6",
    menuRestaurantName: "text-xl sm:text-2xl md:text-3xl font-bold text-white mb-0.5 sm:mb-1",
    menuCuisineType: "text-white/90 text-xs sm:text-sm",
    menuInfoSection: "p-3 sm:p-4 md:p-6 border-b border-gray-200",
    menuInfoGrid: "flex flex-wrap gap-2 sm:gap-3 md:gap-4 mb-3 sm:mb-4",
    menuInfoItem: "flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm md:text-base",
    menuInfoItemText: "text-gray-600",
    menuOfferBanner: "bg-orange-50 border border-orange-200 rounded-lg p-2 sm:p-3 flex items-center gap-1.5 sm:gap-2",
    menuOfferText: "text-xs sm:text-sm font-semibold text-orange-900",
    menuSection: "mb-4 sm:mb-6",
    menuSectionTitle: "text-base sm:text-lg md:text-xl font-bold text-gray-900 mb-1.5 sm:mb-2",
    menuFeatureGrid: "flex flex-wrap gap-1.5 sm:gap-2",
    menuFeatureTag: "px-2.5 sm:px-3 py-1 sm:py-1.5 bg-gray-100 text-gray-700 text-xs sm:text-sm rounded-full",
    menuCategorySection: "space-y-3 sm:space-y-4 md:space-y-6",
    menuCategoryTitle: "text-sm sm:text-base md:text-lg font-bold text-gray-900 pb-1.5 sm:pb-2 border-b-2 border-orange-500 mb-2 sm:mb-3",
    menuItemList: "space-y-1.5 sm:space-y-2 md:space-y-3",
    menuItem: "flex flex-col sm:flex-row sm:justify-between sm:items-start gap-1.5 sm:gap-2 md:gap-4 p-2.5 sm:p-3 hover:bg-gray-50 rounded-lg transition-colors",
    menuItemContent: "flex-1",
    menuItemHeader: "flex items-center gap-1.5 sm:gap-2 mb-0.5 sm:mb-1",
    menuItemName: "font-semibold text-gray-900 text-xs sm:text-sm md:text-base",
    menuItemDescription: "text-xs sm:text-sm text-gray-600",
    menuItemPrice: "font-semibold text-orange-600 whitespace-nowrap text-xs sm:text-sm md:text-base mt-1 sm:mt-0",
}